In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt
import os

%matplotlib inline

In [3]:

seed_urls = ['https://inshorts.com/en/read/technology',
             'https://inshorts.com/en/read/sports',
             'https://inshorts.com/en/read/world']

def build_dataset(seed_urls):
    news_data = []
    for url in seed_urls:
        #gets last part of url to create categories of dataset
        news_category = url.split('/')[-1]
        #request content from url (status of request 200= succesfull, 404 not found= not successfull)
        data = requests.get(url)
        #Represents the document as a nested data structure:
        soup = BeautifulSoup(data.content, 'html.parser')
        #accesing each specific HTML tags
        news_articles = [{'news_headline': headline.find('span', 
                                                         attrs={"itemprop": "headline"}).string,
                          'news_article': article.find('div', 
                                                       attrs={"itemprop": "articleBody"}).string,
                          'news_category': news_category}
                         
                            for headline, article in 
                             zip(soup.find_all('div', 
                                               class_=["news-card-title news-right-box"]),
                                 soup.find_all('div', 
                                               class_=["news-card-content news-right-box"]))
                        ]
        news_data.extend(news_articles)
        
    df =  pd.DataFrame(news_data)
    df = df[['news_headline', 'news_article', 'news_category']]
    return df

In [5]:
#Create dataset with previous function
news_df=build_dataset(seed_urls)
news_df

,news_headline,news_article,news_category
0,Twitter records over 11 lakh tweets on Union B...,Twitter witnessed over 11 lakh Budget-related ...,technology
1,Google responds to 99-smartphone Maps hack tha...,Google has responded to the hack that used 99 ...,technology
2,"Alphabet posts $162B revenue in 2019, reveals ...",Google's parent company Alphabet has posted re...,technology
3,Vine sequel Byte overrun with spam and pornbot...,"Byte, the sequel to 6-second video app Vine, w...",technology
4,Twitter admits 'bad actors' matched numbers wi...,Twitter has revealed that it discovered a secu...,technology
...,...,...,...
70,Couldn't find 1 page with truth: Pelosi on tea...,The US House Speaker Nancy Pelosi on Wednesday...,world
71,Croatia jokingly wishes UK 'good riddance' on ...,While chairing a meeting of European Union (EU...,world
72,Japan prepares ferry to quarantine suspected c...,Japan's Self Defense Force has prepared a ferr...,world
73,No known effective treatment for new coronavir...,After reports emerged of effective treatments ...,world
74,US warns citizens against rising sexual assaul...,A security alert issued by the US Embassy in S...,world

In [6]:
#Total number of news articles
news_df.news_category.value_counts()

world         25
sports        25
technology    25
Name: news_category, dtype: int64